<a href="https://colab.research.google.com/github/Ayanlola2002/DATA-SCIENCE-PROJECTS/blob/master/BP_NLP_PROJECT1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [78]:
import pandas as pd
import re
from google.colab import drive
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Word processing libraries
from nltk.corpus import wordnet
import string
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.tokenize import WhitespaceTokenizer
from nltk.stem import WordNetLemmatizer

import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
from nltk.tokenize import word_tokenize 
from string import punctuation # Importing list of punctuations from string

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [79]:
# you 1st need to right click on the shared folder and select 'Add to my Drive'
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [80]:
data=pd.read_csv("/content/drive/MyDrive/omdena/BP_NLP/Project1/game_reviews.csv")
data

             author age  ...                                             review
0    Teen, 17 years old  ...  Kids dont listent to the parents saying ''ThIs...
1     Kid, 11 years old  ...  I have been playing this game for many years a...
2     Kid, 12 years old  ...  The game is great with no true inappropriate t...
3    Teen, 13 years old  ...  Are you sure you got common sense. I would giv...
4     Kid, 10 years old  ...        IDK WHAT TO SAY BUT DIS IS DA BEST GAME EVA
..                  ...  ...                                                ...
556  Teen, 14 years old  ...  Wow. Just wow. Common Sense, THIS GAME IS IN A...
557  Teen, 13 years old  ...  A quite popular gem on the app store/google pl...
558   Kid, 12 years old  ...  It's a abhorrent try by Mojang, though a excel...
559  Teen, 15 years old  ...  Minecraft: Pocket Edition is an app which you ...
560   Kid, 11 years old  ...  Give it a little time CommonSense, the game is...

[561 rows x 3 columns]

In [81]:
#create an age column
data["age"]= data["author age"].str.extract('(\d+)').astype("float")

In [82]:
data

             author age  ...   age
0    Teen, 17 years old  ...  17.0
1     Kid, 11 years old  ...  11.0
2     Kid, 12 years old  ...  12.0
3    Teen, 13 years old  ...  13.0
4     Kid, 10 years old  ...  10.0
..                  ...  ...   ...
556  Teen, 14 years old  ...  14.0
557  Teen, 13 years old  ...  13.0
558   Kid, 12 years old  ...  12.0
559  Teen, 15 years old  ...  15.0
560   Kid, 11 years old  ...  11.0

[561 rows x 4 columns]

In [83]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 561 entries, 0 to 560
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   author age       561 non-null    object
 1   recommended age  561 non-null    object
 2   review           526 non-null    object
 3   age              561 non-null    float64
dtypes: float64(1), object(3)
memory usage: 17.7+ KB

In [84]:
data.rename(columns={'author age': 'authors_age', 'recommended age': 'recommended_age'}, inplace=True)

In [85]:
#function to create new labeled column
def label(age):
  if age < 10:
    return "Not Suitable"
  else:
    return "Suitable"

#function to get first word
def word(x):
  return x.split(",")[0]

# Define the function to implement POS tagging:
def get_wordnet_pos(pos_tag):
  if pos_tag.startswith('J'):
      return wordnet.ADJ
  elif pos_tag.startswith('V'):
      return wordnet.VERB
  elif pos_tag.startswith('N'):
      return wordnet.NOUN
  elif pos_tag.startswith('R'):
      return wordnet.ADV
  else:
      return wordnet.NOUN


# Define the main function to clean text in various ways:
def clean_text(text):
  # 2. remove URLs
  text = re.sub('((www\.[^\s]+)|(https?://[^\s]+))', '', text)
    
  # 5. Convert text to lowercase
  text = text.lower()
    
  # 6. tokenize text and remove punctuation
  text = [word.strip(string.punctuation) for word in text.split(" ")]
    
  # 7. remove numbers
  text = [word for word in text if not any(c.isdigit() for c in word)]
    
  # 8. remove stop words
  stop = stopwords.words('english')
  text = [x for x in text if x not in stop]
    
  # 9. remove empty tokens
  text = [t for t in text if len(t) > 0]
    
  # 10. pos tag text and lemmatize text
  pos_tags = pos_tag(text)
  text = [WordNetLemmatizer().lemmatize(t[0], get_wordnet_pos(t[1])) for t in pos_tags]
    
  # 11. remove words with only one letter
  text = [t for t in text if len(t) > 1]
    
  # join all
  text = " ".join(text)
    
  return (text)

In [86]:
#Creating the label 
data["label"]=data.apply(lambda x:label(x["age"]),axis=1)

In [87]:
data["review_owner"]=data['authors_age'].apply(lambda x:word(x))

In [88]:
data

            authors_age recommended_age  ...     label  review_owner
0    Teen, 17 years old          age 7+  ...  Suitable          Teen
1     Kid, 11 years old          age 2+  ...  Suitable           Kid
2     Kid, 12 years old          age 7+  ...  Suitable           Kid
3    Teen, 13 years old          age 5+  ...  Suitable          Teen
4     Kid, 10 years old          age 5+  ...  Suitable           Kid
..                  ...             ...  ...       ...           ...
556  Teen, 14 years old          age 7+  ...  Suitable          Teen
557  Teen, 13 years old          age 4+  ...  Suitable          Teen
558   Kid, 12 years old          age 2+  ...  Suitable           Kid
559  Teen, 15 years old          age 6+  ...  Suitable          Teen
560   Kid, 11 years old          age 4+  ...  Suitable           Kid

[561 rows x 6 columns]

In [92]:
#NLP Preprocessing
# Apply function on the column 'text':
data['cleaned_review'] = data['review'].apply(lambda x: clean_text(str(x)))

In [93]:
data

            authors_age  ...                                     cleaned_review
0    Teen, 17 years old  ...  kid dont listent parent say game sword mean vi...
1     Kid, 11 years old  ...  play game many year never get scared nightmare...
2     Kid, 12 years old  ...                game great true inappropriate thing
3    Teen, 13 years old  ...  sure get common sense would give game million ...
4     Kid, 10 years old  ...                       idk say dis da best game eva
..                  ...  ...                                                ...
556  Teen, 14 years old  ...  wow wow common sense game alpha give time alre...
557  Teen, 13 years old  ...  quite popular gem app store/google play basica...
558   Kid, 12 years old  ...  abhorrent try mojang though excellent idea thi...
559  Teen, 15 years old  ...  minecraft pocket edition app download iphone i...
560   Kid, 11 years old  ...  give little time commonsense game alpha receiv...

[561 rows x 7 columns]